# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dataloader.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dataloader.proto',
  package='dataloader',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x64\x61taloader.proto\x12\ndataloader\x1a\x0c\x63ommon.proto\"K\n\x17\x43reateDataloaderRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x61taset_name\x18\x02 \x01(\t\x12\x0c\n\x04nums\x18\x03 \x01(\r\"o\n\x18\x43reateDataloaderResponse\x12\x0e\n\x06length\x18\x01 \x01(\x04\x12\x10\n\x08shm_path\x18\x02 \x01(\t\x12\x11\n\tloader_id\x18\x03 \x01(\x04\x12\x1e\n\x06status\x18\x04 \x01(\x0b\x32\x0e.common.Status\"4\n\x0bNextRequest\x12\x11\n\tloader_id\x18\x01 \x01(\x04\x12\x12\n\nbatch_size\x18\x02 \x01(\x05\"1\n\x0cNextResponse\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x03(\x04\x12\x10\n\x08read_off\x18\x03 \x03(\r\"=\n\x17\x44\x65leteDataloaderRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x61taset_name\x18\x02 \x01(\t\"\x1a\n\x18\x44\x65leteDataloaderResponse\"<\n\x16ResetDataloaderRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x61taset_name\x18\x02 \x01(\t\"\x19\n\x17ResetDataloaderResponse2\xe4\x02\n\rDataLoaderSvc\x12]\n\x10\x43reateDataloader\x12#.dataloader.CreateDataloaderRequest\x1a$.dataloader.CreateDataloaderResponse\x12\x39\n\x04Next\x12\x17.dataloader.NextRequest\x1a\x18.dataloader.NextResponse\x12]\n\x10\x44\x65leteDataloader\x12#.dataloader.DeleteDataloaderRequest\x1a$.dataloader.DeleteDataloaderResponse\x12Z\n\x0fResetDataloader\x12\".dataloader.ResetDataloaderRequest\x1a#.dataloader.ResetDataloaderResponseb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_CREATEDATALOADERREQUEST = _descriptor.Descriptor(
  name='CreateDataloaderRequest',
  full_name='dataloader.CreateDataloaderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='dataloader.CreateDataloaderRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataset_name', full_name='dataloader.CreateDataloaderRequest.dataset_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nums', full_name='dataloader.CreateDataloaderRequest.nums', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=121,
)


_CREATEDATALOADERRESPONSE = _descriptor.Descriptor(
  name='CreateDataloaderResponse',
  full_name='dataloader.CreateDataloaderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='dataloader.CreateDataloaderResponse.length', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shm_path', full_name='dataloader.CreateDataloaderResponse.shm_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loader_id', full_name='dataloader.CreateDataloaderResponse.loader_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='dataloader.CreateDataloaderResponse.status', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=234,
)


_NEXTREQUEST = _descriptor.Descriptor(
  name='NextRequest',
  full_name='dataloader.NextRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='loader_id', full_name='dataloader.NextRequest.loader_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='dataloader.NextRequest.batch_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=288,
)


_NEXTRESPONSE = _descriptor.Descriptor(
  name='NextResponse',
  full_name='dataloader.NextResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='dataloader.NextResponse.address', index=0,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='read_off', full_name='dataloader.NextResponse.read_off', index=1,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=339,
)


_DELETEDATALOADERREQUEST = _descriptor.Descriptor(
  name='DeleteDataloaderRequest',
  full_name='dataloader.DeleteDataloaderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='dataloader.DeleteDataloaderRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataset_name', full_name='dataloader.DeleteDataloaderRequest.dataset_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=402,
)


_DELETEDATALOADERRESPONSE = _descriptor.Descriptor(
  name='DeleteDataloaderResponse',
  full_name='dataloader.DeleteDataloaderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=430,
)


_RESETDATALOADERREQUEST = _descriptor.Descriptor(
  name='ResetDataloaderRequest',
  full_name='dataloader.ResetDataloaderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='dataloader.ResetDataloaderRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataset_name', full_name='dataloader.ResetDataloaderRequest.dataset_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=492,
)


_RESETDATALOADERRESPONSE = _descriptor.Descriptor(
  name='ResetDataloaderResponse',
  full_name='dataloader.ResetDataloaderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=494,
  serialized_end=519,
)

_CREATEDATALOADERRESPONSE.fields_by_name['status'].message_type = common__pb2._STATUS
DESCRIPTOR.message_types_by_name['CreateDataloaderRequest'] = _CREATEDATALOADERREQUEST
DESCRIPTOR.message_types_by_name['CreateDataloaderResponse'] = _CREATEDATALOADERRESPONSE
DESCRIPTOR.message_types_by_name['NextRequest'] = _NEXTREQUEST
DESCRIPTOR.message_types_by_name['NextResponse'] = _NEXTRESPONSE
DESCRIPTOR.message_types_by_name['DeleteDataloaderRequest'] = _DELETEDATALOADERREQUEST
DESCRIPTOR.message_types_by_name['DeleteDataloaderResponse'] = _DELETEDATALOADERRESPONSE
DESCRIPTOR.message_types_by_name['ResetDataloaderRequest'] = _RESETDATALOADERREQUEST
DESCRIPTOR.message_types_by_name['ResetDataloaderResponse'] = _RESETDATALOADERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateDataloaderRequest = _reflection.GeneratedProtocolMessageType('CreateDataloaderRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEDATALOADERREQUEST,
  '__module__' : 'dataloader_pb2'
  # @@protoc_insertion_point(class_scope:dataloader.CreateDataloaderRequest)
  })
_sym_db.RegisterMessage(CreateDataloaderRequest)

CreateDataloaderResponse = _reflection.GeneratedProtocolMessageType('CreateDataloaderResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEDATALOADERRESPONSE,
  '__module__' : 'dataloader_pb2'
  # @@protoc_insertion_point(class_scope:dataloader.CreateDataloaderResponse)
  })
_sym_db.RegisterMessage(CreateDataloaderResponse)

NextRequest = _reflection.GeneratedProtocolMessageType('NextRequest', (_message.Message,), {
  'DESCRIPTOR' : _NEXTREQUEST,
  '__module__' : 'dataloader_pb2'
  # @@protoc_insertion_point(class_scope:dataloader.NextRequest)
  })
_sym_db.RegisterMessage(NextRequest)

NextResponse = _reflection.GeneratedProtocolMessageType('NextResponse', (_message.Message,), {
  'DESCRIPTOR' : _NEXTRESPONSE,
  '__module__' : 'dataloader_pb2'
  # @@protoc_insertion_point(class_scope:dataloader.NextResponse)
  })
_sym_db.RegisterMessage(NextResponse)

DeleteDataloaderRequest = _reflection.GeneratedProtocolMessageType('DeleteDataloaderRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEDATALOADERREQUEST,
  '__module__' : 'dataloader_pb2'
  # @@protoc_insertion_point(class_scope:dataloader.DeleteDataloaderRequest)
  })
_sym_db.RegisterMessage(DeleteDataloaderRequest)

DeleteDataloaderResponse = _reflection.GeneratedProtocolMessageType('DeleteDataloaderResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEDATALOADERRESPONSE,
  '__module__' : 'dataloader_pb2'
  # @@protoc_insertion_point(class_scope:dataloader.DeleteDataloaderResponse)
  })
_sym_db.RegisterMessage(DeleteDataloaderResponse)

ResetDataloaderRequest = _reflection.GeneratedProtocolMessageType('ResetDataloaderRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESETDATALOADERREQUEST,
  '__module__' : 'dataloader_pb2'
  # @@protoc_insertion_point(class_scope:dataloader.ResetDataloaderRequest)
  })
_sym_db.RegisterMessage(ResetDataloaderRequest)

ResetDataloaderResponse = _reflection.GeneratedProtocolMessageType('ResetDataloaderResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESETDATALOADERRESPONSE,
  '__module__' : 'dataloader_pb2'
  # @@protoc_insertion_point(class_scope:dataloader.ResetDataloaderResponse)
  })
_sym_db.RegisterMessage(ResetDataloaderResponse)



_DATALOADERSVC = _descriptor.ServiceDescriptor(
  name='DataLoaderSvc',
  full_name='dataloader.DataLoaderSvc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=522,
  serialized_end=878,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateDataloader',
    full_name='dataloader.DataLoaderSvc.CreateDataloader',
    index=0,
    containing_service=None,
    input_type=_CREATEDATALOADERREQUEST,
    output_type=_CREATEDATALOADERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Next',
    full_name='dataloader.DataLoaderSvc.Next',
    index=1,
    containing_service=None,
    input_type=_NEXTREQUEST,
    output_type=_NEXTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteDataloader',
    full_name='dataloader.DataLoaderSvc.DeleteDataloader',
    index=2,
    containing_service=None,
    input_type=_DELETEDATALOADERREQUEST,
    output_type=_DELETEDATALOADERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ResetDataloader',
    full_name='dataloader.DataLoaderSvc.ResetDataloader',
    index=3,
    containing_service=None,
    input_type=_RESETDATALOADERREQUEST,
    output_type=_RESETDATALOADERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATALOADERSVC)

DESCRIPTOR.services_by_name['DataLoaderSvc'] = _DATALOADERSVC

# @@protoc_insertion_point(module_scope)
